version: "3.0"
networks:
  services-network:
    driver: bridge
volumes:
  postgres_data:
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./backend:/backend
    environment:
      DB_USER: postgres
      DB_HOST: db
      DB_PASSWORD: root
      DB_NAME: shop_database
      DB_PORT: 5432
    ports:
      - "8000:8000"
    networks:
      - services-network
    restart: always
  db:
    image: postgres:13-alpine
    volumes:
      - ./pg_init_scripts:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    networks:
      - services-network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - services-network
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: always