"""empty message

Revision ID: 0241f2d5ce60
Revises: 5beed2affa82
Create Date: 2023-04-25 22:37:37.680775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0241f2d5ce60'
down_revision = '5beed2affa82'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
