"""empty message

Revision ID: 02c54217866d
Revises: 9b8ad3a4020f
Create Date: 2023-04-24 21:52:44.041747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02c54217866d'
down_revision = '9b8ad3a4020f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
