"""empty message

Revision ID: 03165fe1e328
Revises: b3f6697278d0
Create Date: 2023-04-26 09:37:17.197955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03165fe1e328'
down_revision = 'b3f6697278d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
