"""empty message

Revision ID: 03654b68b8ac
Revises: 6a769b0c8b6a
Create Date: 2023-04-24 20:59:30.217261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03654b68b8ac'
down_revision = '6a769b0c8b6a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
