"""empty message

Revision ID: 04367475a414
Revises: b759d15291e6
Create Date: 2023-04-25 20:24:42.274281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04367475a414'
down_revision = 'b759d15291e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
