"""empty message

Revision ID: 059333ad5691
Revises: 868c392bfb22
Create Date: 2023-04-25 21:50:04.213130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '059333ad5691'
down_revision = '868c392bfb22'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
