"""empty message

Revision ID: 065d48ed00ba
Revises: d8b591da468f
Create Date: 2023-04-24 18:06:42.869859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '065d48ed00ba'
down_revision = 'd8b591da468f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img_url', sa.String(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    # ### end Alembic commands ###
