"""empty message

Revision ID: 07cbb90cf224
Revises: 37601ecf2ef7
Create Date: 2023-04-25 18:16:03.884509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07cbb90cf224'
down_revision = '37601ecf2ef7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
