"""empty message

Revision ID: 08f9da057eea
Revises: 78d6de6f12b4
Create Date: 2023-04-27 20:56:51.090461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08f9da057eea'
down_revision = '78d6de6f12b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
