"""empty message

Revision ID: 093cf08ff6dd
Revises: 2fa92145a205
Create Date: 2023-04-27 20:19:09.791582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '093cf08ff6dd'
down_revision = '2fa92145a205'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
