"""empty message

Revision ID: 099f682b1f47
Revises: f5b95f529ca6
Create Date: 2023-04-26 22:09:46.527716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '099f682b1f47'
down_revision = 'f5b95f529ca6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
