"""empty message

Revision ID: 0a0cd43fd499
Revises: 484b8208bc1c
Create Date: 2023-04-27 19:09:50.521450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a0cd43fd499'
down_revision = '484b8208bc1c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
