"""empty message

Revision ID: 0e382285ed39
Revises: 5e6ebfaff49b
Create Date: 2023-04-26 08:57:19.215367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e382285ed39'
down_revision = '5e6ebfaff49b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
