"""empty message

Revision ID: 1007ac519562
Revises: 95ca73c31f72
Create Date: 2023-04-27 14:21:13.132730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1007ac519562'
down_revision = '95ca73c31f72'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
