"""empty message

Revision ID: 114727d27913
Revises: f89481368bcb
Create Date: 2023-04-26 09:08:04.839735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '114727d27913'
down_revision = 'f89481368bcb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
