"""empty message

Revision ID: 1236a7a67c88
Revises: c04b902b8ff7
Create Date: 2023-04-24 20:14:58.915591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1236a7a67c88'
down_revision = 'c04b902b8ff7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
