"""empty message

Revision ID: 12ce6c7facc1
Revises: 980c11fb28b0
Create Date: 2023-04-25 10:54:00.297647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12ce6c7facc1'
down_revision = '980c11fb28b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
