"""empty message

Revision ID: 1376b94aea40
Revises: c7ddc051094f
Create Date: 2023-04-26 08:34:58.900487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1376b94aea40'
down_revision = 'c7ddc051094f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
