"""empty message

Revision ID: 176de525a51a
Revises: 8dd5e4ed5338
Create Date: 2023-04-27 23:08:40.902884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '176de525a51a'
down_revision = '8dd5e4ed5338'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
