"""empty message

Revision ID: 179679101b63
Revises: aa666c2d2479
Create Date: 2023-04-25 11:16:25.745134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '179679101b63'
down_revision = 'aa666c2d2479'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
