"""empty message

Revision ID: 19056a534ca5
Revises: 31ebf000767e
Create Date: 2023-04-25 22:20:09.194479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19056a534ca5'
down_revision = '31ebf000767e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
