"""empty message

Revision ID: 1983b2f6b7f9
Revises: a8899886cde5
Create Date: 2023-04-26 21:16:37.030191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1983b2f6b7f9'
down_revision = 'a8899886cde5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
