"""empty message

Revision ID: 1c3a8625bf95
Revises: 1983b2f6b7f9
Create Date: 2023-04-26 21:21:19.067805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c3a8625bf95'
down_revision = '1983b2f6b7f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
