"""empty message

Revision ID: 1c5255bf310e
Revises: d127fe58cbfa
Create Date: 2023-04-27 22:30:09.908401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c5255bf310e'
down_revision = 'd127fe58cbfa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
