"""empty message

Revision ID: 1c729e25244a
Revises: 093cf08ff6dd
Create Date: 2023-04-27 20:48:47.058746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c729e25244a'
down_revision = '093cf08ff6dd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
