"""empty message

Revision ID: 1d5d01304af4
Revises: 4b74146186e3
Create Date: 2023-04-25 20:04:18.164460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d5d01304af4'
down_revision = '4b74146186e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
