"""empty message

Revision ID: 1f4a35f09db4
Revises: 249cb02f3bab
Create Date: 2023-04-27 17:06:22.573476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f4a35f09db4'
down_revision = '249cb02f3bab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
