"""empty message

Revision ID: 2050a20d87e1
Revises: 3d0063d91993
Create Date: 2023-04-24 22:43:34.828800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2050a20d87e1'
down_revision = '3d0063d91993'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
