"""empty message

Revision ID: 205050187646
Revises: 97f65beaaacf
Create Date: 2023-04-27 23:35:55.744004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '205050187646'
down_revision = '97f65beaaacf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
