"""empty message

Revision ID: 209f02be2785
Revises: 23459a3a6d71
Create Date: 2023-04-27 21:17:28.848652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '209f02be2785'
down_revision = '23459a3a6d71'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
