"""empty message

Revision ID: 20bdf420de63
Revises: fa6133043638
Create Date: 2023-04-26 00:22:16.240010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20bdf420de63'
down_revision = 'fa6133043638'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
