"""empty message

Revision ID: 21d3cda8e5f0
Revises: cd58aa6ac7d1
Create Date: 2023-04-27 17:42:12.215768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21d3cda8e5f0'
down_revision = 'cd58aa6ac7d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
