"""empty message

Revision ID: 23459a3a6d71
Revises: 37d4fa00ae14
Create Date: 2023-04-27 21:10:27.385568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23459a3a6d71'
down_revision = '37d4fa00ae14'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
