"""empty message

Revision ID: 23bb7b92208d
Revises: 60472f08a124
Create Date: 2023-04-26 08:01:54.739057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23bb7b92208d'
down_revision = '60472f08a124'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
