"""empty message

Revision ID: 246b88663cc4
Revises: 5dda3b3054f6
Create Date: 2023-04-25 20:48:24.844689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '246b88663cc4'
down_revision = '5dda3b3054f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
