"""empty message

Revision ID: 249cb02f3bab
Revises: 2f60fc21f0af
Create Date: 2023-04-27 16:58:48.111224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '249cb02f3bab'
down_revision = '2f60fc21f0af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
