"""empty message

Revision ID: 24e5fe8eb6fd
Revises: d1444580a551
Create Date: 2023-04-28 00:22:47.349705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24e5fe8eb6fd'
down_revision = 'd1444580a551'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
