"""empty message

Revision ID: 261a89bd97d8
Revises: 29690e5b093a
Create Date: 2023-04-26 23:17:23.713736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '261a89bd97d8'
down_revision = '29690e5b093a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
