"""empty message

Revision ID: 284ba05b9461
Revises: 12ce6c7facc1
Create Date: 2023-04-25 10:58:28.380215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '284ba05b9461'
down_revision = '12ce6c7facc1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
