"""empty message

Revision ID: 29690e5b093a
Revises: 3341ec5e5c54
Create Date: 2023-04-26 23:11:30.171668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29690e5b093a'
down_revision = '3341ec5e5c54'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
