"""empty message

Revision ID: 29a67250f596
Revises: 261a89bd97d8
Create Date: 2023-04-26 23:21:00.061359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29a67250f596'
down_revision = '261a89bd97d8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
