"""empty message

Revision ID: 2c82946df0fe
Revises: 3dc6c0a461de
Create Date: 2023-04-27 15:48:35.122432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c82946df0fe'
down_revision = '3dc6c0a461de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
