"""empty message

Revision ID: 2ce032b95af5
Revises: 07cbb90cf224
Create Date: 2023-04-25 18:27:07.384631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ce032b95af5'
down_revision = '07cbb90cf224'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
