"""empty message

Revision ID: 2f60fc21f0af
Revises: ca9075d7ba18
Create Date: 2023-04-27 16:55:55.526890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f60fc21f0af'
down_revision = 'ca9075d7ba18'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
