"""empty message

Revision ID: 2fa92145a205
Revises: d2e3d013f355
Create Date: 2023-04-27 20:16:47.088985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fa92145a205'
down_revision = 'd2e3d013f355'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
