"""empty message

Revision ID: 2fd1475d07e4
Revises: 065d48ed00ba
Create Date: 2023-04-24 18:23:32.521069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fd1475d07e4'
down_revision = '065d48ed00ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
