"""empty message

Revision ID: 30b60a8a39b1
Revises: 84a67f003834
Create Date: 2023-04-25 19:04:29.957711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30b60a8a39b1'
down_revision = '84a67f003834'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
