"""empty message

Revision ID: 313e4063658a
Revises: 2050a20d87e1
Create Date: 2023-04-24 22:48:55.063965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '313e4063658a'
down_revision = '2050a20d87e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
