"""empty message

Revision ID: 315b87c8f5ed
Revises: 1d5d01304af4
Create Date: 2023-04-25 20:13:33.255250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '315b87c8f5ed'
down_revision = '1d5d01304af4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
