"""empty message

Revision ID: 31ace02e2183
Revises: da6153a7c58e
Create Date: 2023-04-27 16:03:29.258622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31ace02e2183'
down_revision = 'da6153a7c58e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
