"""empty message

Revision ID: 31ebf000767e
Revises: 6598d2a5e4f0
Create Date: 2023-04-25 22:17:44.959926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31ebf000767e'
down_revision = '6598d2a5e4f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
