"""empty message

Revision ID: 3341ec5e5c54
Revises: ef6284eba194
Create Date: 2023-04-26 22:33:16.992532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3341ec5e5c54'
down_revision = 'ef6284eba194'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
