"""empty message

Revision ID: 34b4bb4074bd
Revises: 099f682b1f47
Create Date: 2023-04-26 22:13:08.105507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34b4bb4074bd'
down_revision = '099f682b1f47'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
