"""empty message

Revision ID: 3646a438e1a1
Revises: c237d5038c62
Create Date: 2023-04-24 19:53:10.180551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3646a438e1a1'
down_revision = 'c237d5038c62'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
