"""empty message

Revision ID: 371ab7e4f22f
Revises: b1d6f4e779eb
Create Date: 2023-04-24 22:07:13.552785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '371ab7e4f22f'
down_revision = 'b1d6f4e779eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
