"""empty message

Revision ID: 37601ecf2ef7
Revises: adfda3ece0e5
Create Date: 2023-04-25 18:12:38.484997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37601ecf2ef7'
down_revision = 'adfda3ece0e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
