"""empty message

Revision ID: 37d4fa00ae14
Revises: 08f9da057eea
Create Date: 2023-04-27 21:05:46.988001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37d4fa00ae14'
down_revision = '08f9da057eea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
