"""empty message

Revision ID: 38be2bdabeb3
Revises: 68c214eb2fed
Create Date: 2023-04-25 21:12:29.495160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38be2bdabeb3'
down_revision = '68c214eb2fed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
