"""empty message

Revision ID: 3b62d7432203
Revises: fcdffe5b0535
Create Date: 2023-04-25 22:05:17.732358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b62d7432203'
down_revision = 'fcdffe5b0535'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
