"""empty message

Revision ID: 3c474c09d77e
Revises: 6d9fe0e3e724
Create Date: 2023-04-26 21:54:44.979641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c474c09d77e'
down_revision = '6d9fe0e3e724'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
