"""empty message

Revision ID: 3d0063d91993
Revises: 8efeb35ed84a
Create Date: 2023-04-24 22:31:24.958071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d0063d91993'
down_revision = '8efeb35ed84a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
