"""empty message

Revision ID: 3db67f4f1c7c
Revises: 824133c1b6f7
Create Date: 2023-04-25 19:47:24.611514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3db67f4f1c7c'
down_revision = '824133c1b6f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
