"""empty message

Revision ID: 3dc6c0a461de
Revises: fc0abce506f9
Create Date: 2023-04-27 14:31:46.075860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dc6c0a461de'
down_revision = 'fc0abce506f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
