"""empty message

Revision ID: 3e8e357080ca
Revises: cc951d36a624
Create Date: 2023-04-26 20:55:30.866758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e8e357080ca'
down_revision = 'cc951d36a624'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
