"""empty message

Revision ID: 40f4bf6a2e8b
Revises: 24e5fe8eb6fd
Create Date: 2023-04-28 00:25:35.569380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40f4bf6a2e8b'
down_revision = '24e5fe8eb6fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
