"""empty message

Revision ID: 43661ccb4e0f
Revises: 61219793278b
Create Date: 2023-04-27 13:37:42.509967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43661ccb4e0f'
down_revision = '61219793278b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
