"""empty message

Revision ID: 47b896cbb2fa
Revises: 3e8e357080ca
Create Date: 2023-04-26 21:02:28.818662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47b896cbb2fa'
down_revision = '3e8e357080ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
