"""empty message

Revision ID: 484b8208bc1c
Revises: 73f993ef51aa
Create Date: 2023-04-27 19:07:10.657253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '484b8208bc1c'
down_revision = '73f993ef51aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
