"""empty message

Revision ID: 4b16960c1168
Revises: 34b4bb4074bd
Create Date: 2023-04-26 22:17:11.171319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b16960c1168'
down_revision = '34b4bb4074bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
