"""empty message

Revision ID: 4b74146186e3
Revises: cfcdd0f45bd1
Create Date: 2023-04-25 19:59:06.656826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b74146186e3'
down_revision = 'cfcdd0f45bd1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
