"""empty message

Revision ID: 4f6e364666a2
Revises: d3422a7650e6
Create Date: 2023-04-27 22:07:58.012057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f6e364666a2'
down_revision = 'd3422a7650e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
