"""empty message

Revision ID: 4feed2767187
Revises: 1f4a35f09db4
Create Date: 2023-04-27 17:12:35.613644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4feed2767187'
down_revision = '1f4a35f09db4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
