"""empty message

Revision ID: 4ff1679cf5fa
Revises: 509979a0ea0f
Create Date: 2023-04-25 18:33:37.596297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ff1679cf5fa'
down_revision = '509979a0ea0f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
