"""empty message

Revision ID: 504b6efbe9a3
Revises: 9044ecb57c8e
Create Date: 2023-04-27 16:41:07.204107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '504b6efbe9a3'
down_revision = '9044ecb57c8e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
