"""empty message

Revision ID: 509979a0ea0f
Revises: 2ce032b95af5
Create Date: 2023-04-25 18:29:09.702911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '509979a0ea0f'
down_revision = '2ce032b95af5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
