"""empty message

Revision ID: 547e8615a35c
Revises: 55e376202546
Create Date: 2023-04-24 19:59:39.213775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '547e8615a35c'
down_revision = '55e376202546'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
