"""empty message

Revision ID: 54dc4314acfc
Revises: 43661ccb4e0f
Create Date: 2023-04-27 13:44:33.576010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54dc4314acfc'
down_revision = '43661ccb4e0f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
