"""empty message

Revision ID: 54eed2350a34
Revises: 21d3cda8e5f0
Create Date: 2023-04-27 18:12:08.040288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54eed2350a34'
down_revision = '21d3cda8e5f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
