"""empty message

Revision ID: 573a81bc7b3c
Revises: 03165fe1e328
Create Date: 2023-04-26 09:41:29.078737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '573a81bc7b3c'
down_revision = '03165fe1e328'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
