"""empty message

Revision ID: 5e6ebfaff49b
Revises: f0521f222d87
Create Date: 2023-04-26 08:50:27.304311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e6ebfaff49b'
down_revision = 'f0521f222d87'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
