"""empty message

Revision ID: 60472f08a124
Revises: eb18c3d75db5
Create Date: 2023-04-26 07:57:54.147662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60472f08a124'
down_revision = 'eb18c3d75db5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
