"""empty message

Revision ID: 61219793278b
Revises: d2314e073f59
Create Date: 2023-04-27 13:29:09.207106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61219793278b'
down_revision = 'd2314e073f59'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
