"""empty message

Revision ID: 61348a102743
Revises: d7dc2b761757
Create Date: 2023-04-27 19:26:38.238926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61348a102743'
down_revision = 'd7dc2b761757'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
