"""empty message

Revision ID: 61bab7cb85a3
Revises: 3a715bba6453
Create Date: 2023-04-28 00:06:39.819509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61bab7cb85a3'
down_revision = '3a715bba6453'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
