"""empty message

Revision ID: 6598d2a5e4f0
Revises: 3b62d7432203
Create Date: 2023-04-25 22:09:01.795352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6598d2a5e4f0'
down_revision = '3b62d7432203'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
