"""empty message

Revision ID: 68751d09b017
Revises: 6f736011dac5
Create Date: 2023-04-26 09:58:39.422503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68751d09b017'
down_revision = '6f736011dac5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
