"""empty message

Revision ID: 68c214eb2fed
Revises: ef6f30338ebc
Create Date: 2023-04-25 21:05:21.700067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68c214eb2fed'
down_revision = 'ef6f30338ebc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
