"""empty message

Revision ID: 6a769b0c8b6a
Revises: d5e1a0fd667d
Create Date: 2023-04-24 20:52:58.494687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a769b0c8b6a'
down_revision = 'd5e1a0fd667d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
