"""empty message

Revision ID: 6af650c0fb55
Revises: fe42a1d4a791
Create Date: 2023-04-25 19:20:59.100310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6af650c0fb55'
down_revision = 'fe42a1d4a791'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
