"""empty message

Revision ID: 6b5c12802dc7
Revises: 246b88663cc4
Create Date: 2023-04-25 20:54:09.804946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b5c12802dc7'
down_revision = '246b88663cc4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
