"""empty message

Revision ID: 6b78416fbc44
Revises: 2fd1475d07e4
Create Date: 2023-04-24 19:00:23.436055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b78416fbc44'
down_revision = '2fd1475d07e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
