"""empty message

Revision ID: 6d9fe0e3e724
Revises: 81e49ae6603e
Create Date: 2023-04-26 21:41:08.746340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d9fe0e3e724'
down_revision = '81e49ae6603e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
