"""empty message

Revision ID: 6df0881901c7
Revises: b05408bf31ab
Create Date: 2023-04-26 19:27:50.097420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6df0881901c7'
down_revision = 'b05408bf31ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
