"""empty message

Revision ID: 6e9dfb00f1d6
Revises: 8d6c3fc31f6d
Create Date: 2023-04-27 22:19:16.504607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e9dfb00f1d6'
down_revision = '8d6c3fc31f6d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
