"""empty message

Revision ID: 6f736011dac5
Revises: 573a81bc7b3c
Create Date: 2023-04-26 09:51:33.971359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f736011dac5'
down_revision = '573a81bc7b3c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
