"""empty message

Revision ID: 7001d0fd21e9
Revises: 38be2bdabeb3
Create Date: 2023-04-25 21:32:09.374777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7001d0fd21e9'
down_revision = '38be2bdabeb3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
