"""empty message

Revision ID: 71ac13e2e4c4
Revises: 1c5255bf310e
Create Date: 2023-04-27 22:34:43.878293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71ac13e2e4c4'
down_revision = '1c5255bf310e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
