"""empty message

Revision ID: 72b82e5ef5ca
Revises: d33f3a5774ad
Create Date: 2023-04-27 16:26:32.537425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72b82e5ef5ca'
down_revision = 'd33f3a5774ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
