"""empty message

Revision ID: 73f993ef51aa
Revises: 0912c8545257
Create Date: 2023-04-27 19:03:35.355119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73f993ef51aa'
down_revision = '0912c8545257'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
