"""empty message

Revision ID: 75f568078e87
Revises: ef876385cda4
Create Date: 2023-04-27 22:00:50.833058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75f568078e87'
down_revision = 'ef876385cda4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
