"""empty message

Revision ID: 76a2db8d989c
Revises: 313e4063658a
Create Date: 2023-04-24 23:03:45.251308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76a2db8d989c'
down_revision = '313e4063658a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
