"""empty message

Revision ID: 78d6de6f12b4
Revises: 1c729e25244a
Create Date: 2023-04-27 20:52:04.337189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78d6de6f12b4'
down_revision = '1c729e25244a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
