"""empty message

Revision ID: 7a23978a50d6
Revises: 284ba05b9461
Create Date: 2023-04-25 11:02:52.598767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a23978a50d6'
down_revision = '284ba05b9461'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
