"""empty message

Revision ID: 7a6eecb75551
Revises: 9fa5342e1706
Create Date: 2023-04-24 21:36:53.419675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a6eecb75551'
down_revision = '9fa5342e1706'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
