"""empty message

Revision ID: 7ccff4ebd3c4
Revises: 3c474c09d77e
Create Date: 2023-04-26 21:57:22.127677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ccff4ebd3c4'
down_revision = '3c474c09d77e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
