"""empty message

Revision ID: 7d9776ee7629
Revises: d8d47ae6e3fc
Create Date: 2023-04-27 21:53:13.252910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d9776ee7629'
down_revision = 'd8d47ae6e3fc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
