"""empty message

Revision ID: 7ece4129ca9f
Revises: 54eed2350a34
Create Date: 2023-04-27 18:23:48.101863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ece4129ca9f'
down_revision = '54eed2350a34'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
