"""empty message

Revision ID: 814fba415e72
Revises: b7ab70fcb821
Create Date: 2023-04-25 23:01:24.705855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '814fba415e72'
down_revision = 'b7ab70fcb821'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
