"""empty message

Revision ID: 81917b6747f1
Revises: efa921da80bf
Create Date: 2023-04-27 18:49:24.693076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81917b6747f1'
down_revision = 'efa921da80bf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
