"""empty message

Revision ID: 81e49ae6603e
Revises: 1c3a8625bf95
Create Date: 2023-04-26 21:27:39.503348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81e49ae6603e'
down_revision = '1c3a8625bf95'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
