"""empty message

Revision ID: 823d42e05878
Revises: 329cb31f286e
Create Date: 2023-04-27 16:50:16.987664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '823d42e05878'
down_revision = '329cb31f286e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
