"""empty message

Revision ID: 824133c1b6f7
Revises: d2481f2e7225
Create Date: 2023-04-25 19:40:51.499981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '824133c1b6f7'
down_revision = 'd2481f2e7225'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
