"""empty message

Revision ID: 843c4e7e7a21
Revises: a3bf80079421
Create Date: 2023-04-28 14:56:13.960218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '843c4e7e7a21'
down_revision = 'a3bf80079421'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
