"""empty message

Revision ID: 84a67f003834
Revises: eaf83f2f36ad
Create Date: 2023-04-25 19:02:26.129264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84a67f003834'
down_revision = 'eaf83f2f36ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
