"""empty message

Revision ID: 868c392bfb22
Revises: 0ddba673699f
Create Date: 2023-04-25 21:47:06.816918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '868c392bfb22'
down_revision = '0ddba673699f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
