"""empty message

Revision ID: 86b9218e0173
Revises: bd433739338d
Create Date: 2023-04-26 08:25:32.247833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86b9218e0173'
down_revision = 'bd433739338d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
