"""empty message

Revision ID: 89a6459c31ba
Revises: b06bba21ae42
Create Date: 2023-04-24 20:47:57.831115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89a6459c31ba'
down_revision = 'b06bba21ae42'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
