"""empty message

Revision ID: 89eee7721073
Revises: 71ac13e2e4c4
Create Date: 2023-04-27 22:58:10.791557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89eee7721073'
down_revision = '71ac13e2e4c4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
