"""empty message

Revision ID: 8ae2daf18a13
Revises: d8c68e12cbea
Create Date: 2023-04-25 23:50:43.700947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ae2daf18a13'
down_revision = 'd8c68e12cbea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
