"""empty message

Revision ID: 8b0af14bdfa3
Revises: f607ccbcc762
Create Date: 2023-04-26 08:43:16.443482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b0af14bdfa3'
down_revision = 'f607ccbcc762'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
