"""empty message

Revision ID: 8dd5e4ed5338
Revises: 89eee7721073
Create Date: 2023-04-27 23:03:24.338758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dd5e4ed5338'
down_revision = '89eee7721073'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
