"""empty message

Revision ID: 8efeb35ed84a
Revises: ae57ab550a1c
Create Date: 2023-04-24 22:19:15.002089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8efeb35ed84a'
down_revision = 'ae57ab550a1c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
