"""empty message

Revision ID: 8f54787e7e07
Revises: c1c082461b49
Create Date: 2023-04-25 18:46:44.677009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f54787e7e07'
down_revision = 'c1c082461b49'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
