"""empty message

Revision ID: 9044ecb57c8e
Revises: 72b82e5ef5ca
Create Date: 2023-04-27 16:31:26.473133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9044ecb57c8e'
down_revision = '72b82e5ef5ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
