"""empty message

Revision ID: 912cef30ca68
Revises: 02c54217866d
Create Date: 2023-04-24 22:00:50.310477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '912cef30ca68'
down_revision = '02c54217866d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
