"""empty message

Revision ID: 9291a5a265fc
Revises: 30b60a8a39b1
Create Date: 2023-04-25 19:07:28.246274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9291a5a265fc'
down_revision = '30b60a8a39b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
