"""empty message

Revision ID: 92cbc6909aeb
Revises: 8f54787e7e07
Create Date: 2023-04-25 19:00:08.502657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92cbc6909aeb'
down_revision = '8f54787e7e07'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
