"""empty message

Revision ID: 94b4e7f6500d
Revises: c31f49b382c3
Create Date: 2023-04-25 18:00:10.520937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94b4e7f6500d'
down_revision = 'c31f49b382c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
