"""empty message

Revision ID: 95ca73c31f72
Revises: 54dc4314acfc
Create Date: 2023-04-27 13:52:58.131130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95ca73c31f72'
down_revision = '54dc4314acfc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
