"""empty message

Revision ID: 97f65beaaacf
Revises: 176de525a51a
Create Date: 2023-04-27 23:11:56.110658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97f65beaaacf'
down_revision = '176de525a51a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
