"""empty message

Revision ID: 980c11fb28b0
Revises: e3663fb80a02
Create Date: 2023-04-25 00:05:59.444718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '980c11fb28b0'
down_revision = 'e3663fb80a02'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
