"""empty message

Revision ID: 98f2cc5719a3
Revises: 8ae2daf18a13
Create Date: 2023-04-25 23:55:02.011034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98f2cc5719a3'
down_revision = '8ae2daf18a13'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
