"""empty message

Revision ID: 992298a70f12
Revises: 47b896cbb2fa
Create Date: 2023-04-26 21:10:43.936266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '992298a70f12'
down_revision = '47b896cbb2fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
