"""empty message

Revision ID: 9a8c09202c9b
Revises: 31ace02e2183
Create Date: 2023-04-27 16:11:19.685980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a8c09202c9b'
down_revision = '31ace02e2183'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
