"""empty message

Revision ID: 9afa92c42afe
Revises: c3904c22c5fa
Create Date: 2023-04-27 17:34:39.226920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9afa92c42afe'
down_revision = 'c3904c22c5fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
