"""empty message

Revision ID: 9b6dc5b0b980
Revises: 1236a7a67c88
Create Date: 2023-04-24 20:40:38.646165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b6dc5b0b980'
down_revision = '1236a7a67c88'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
