"""empty message

Revision ID: 9b8ad3a4020f
Revises: f52f9a521ee5
Create Date: 2023-04-24 21:49:04.697461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b8ad3a4020f'
down_revision = 'f52f9a521ee5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
