"""empty message

Revision ID: 9fa5342e1706
Revises: 03654b68b8ac
Create Date: 2023-04-24 21:17:34.639449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fa5342e1706'
down_revision = '03654b68b8ac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
