"""empty message

Revision ID: a3bf80079421
Revises: 40f4bf6a2e8b
Create Date: 2023-04-28 00:28:12.809531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3bf80079421'
down_revision = '40f4bf6a2e8b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
