"""empty message

Revision ID: a4bb3b7a835b
Revises: a4fda12f5741
Create Date: 2023-04-27 21:46:59.598673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4bb3b7a835b'
down_revision = 'a4fda12f5741'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
