"""empty message

Revision ID: a4fda12f5741
Revises: ed94b4839124
Create Date: 2023-04-27 21:42:25.610823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4fda12f5741'
down_revision = 'ed94b4839124'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
