"""empty message

Revision ID: a5b1f52da296
Revises: 3db67f4f1c7c
Create Date: 2023-04-25 19:50:05.109307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5b1f52da296'
down_revision = '3db67f4f1c7c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
