"""empty message

Revision ID: aa666c2d2479
Revises: 7a23978a50d6
Create Date: 2023-04-25 11:15:10.205161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa666c2d2479'
down_revision = '7a23978a50d6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
