"""empty message

Revision ID: ab1ba9023ded
Revises: b695614f7f5e
Create Date: 2023-04-27 21:34:31.819657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab1ba9023ded'
down_revision = 'b695614f7f5e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
