"""empty message

Revision ID: ab93aaf83b54
Revises: 1007ac519562
Create Date: 2023-04-27 14:24:08.100559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab93aaf83b54'
down_revision = '1007ac519562'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
