"""empty message

Revision ID: adfda3ece0e5
Revises: 94b4e7f6500d
Create Date: 2023-04-25 18:09:21.012063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adfda3ece0e5'
down_revision = '94b4e7f6500d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
