"""empty message

Revision ID: ae57ab550a1c
Revises: 371ab7e4f22f
Create Date: 2023-04-24 22:11:30.129056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae57ab550a1c'
down_revision = '371ab7e4f22f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
