"""empty message

Revision ID: b05408bf31ab
Revises: dbb89cf4386f
Create Date: 2023-04-26 13:53:32.072040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b05408bf31ab'
down_revision = 'dbb89cf4386f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
