"""empty message

Revision ID: b1d6f4e779eb
Revises: 35932f4444d3
Create Date: 2023-04-24 22:04:31.609555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1d6f4e779eb'
down_revision = '35932f4444d3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
