"""empty message

Revision ID: b3f6697278d0
Revises: 4e24e4abdeff
Create Date: 2023-04-26 09:34:30.420137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3f6697278d0'
down_revision = '4e24e4abdeff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
