"""empty message

Revision ID: b695614f7f5e
Revises: aacdd85678c2
Create Date: 2023-04-27 21:31:32.669561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b695614f7f5e'
down_revision = 'aacdd85678c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
