"""empty message

Revision ID: b759d15291e6
Revises: 315b87c8f5ed
Create Date: 2023-04-25 20:17:27.433650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b759d15291e6'
down_revision = '315b87c8f5ed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
