"""empty message

Revision ID: b7ab70fcb821
Revises: d8f806c550e7
Create Date: 2023-04-25 22:59:38.957741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7ab70fcb821'
down_revision = 'd8f806c550e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
