"""empty message

Revision ID: ba54df45e5aa
Revises: bd652cc7f4ed
Create Date: 2023-04-25 16:56:32.714183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba54df45e5aa'
down_revision = 'bd652cc7f4ed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
