"""empty message

Revision ID: bbfccbbc54bb
Revises: ba54df45e5aa
Create Date: 2023-04-25 17:05:55.038154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbfccbbc54bb'
down_revision = 'ba54df45e5aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
