"""empty message

Revision ID: bd652cc7f4ed
Revises: d5e34416d804
Create Date: 2023-04-25 16:25:19.494701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd652cc7f4ed'
down_revision = 'd5e34416d804'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
