"""empty message

Revision ID: c04b902b8ff7
Revises: 547e8615a35c
Create Date: 2023-04-24 20:11:42.073686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c04b902b8ff7'
down_revision = '547e8615a35c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
