"""empty message

Revision ID: c1985185c208
Revises: d0ee76a0886b
Create Date: 2023-04-24 23:27:35.960044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1985185c208'
down_revision = 'd0ee76a0886b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
