"""empty message

Revision ID: c1c082461b49
Revises: 4ff1679cf5fa
Create Date: 2023-04-25 18:42:28.956785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1c082461b49'
down_revision = '4ff1679cf5fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
