"""empty message

Revision ID: c237d5038c62
Revises: 42f4f475c540
Create Date: 2023-04-24 19:36:12.848117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c237d5038c62'
down_revision = '42f4f475c540'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
