"""empty message

Revision ID: c3904c22c5fa
Revises: 7e36418e097c
Create Date: 2023-04-27 17:31:51.391038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3904c22c5fa'
down_revision = '7e36418e097c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
