"""empty message

Revision ID: c5c38d405493
Revises: 7001d0fd21e9
Create Date: 2023-04-25 21:35:09.225954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5c38d405493'
down_revision = '7001d0fd21e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
