"""empty message

Revision ID: ca9075d7ba18
Revises: 823d42e05878
Create Date: 2023-04-27 16:54:23.887826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca9075d7ba18'
down_revision = '823d42e05878'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
