"""empty message

Revision ID: cb003f6ce69a
Revises: 0a0cd43fd499
Create Date: 2023-04-27 19:14:49.609973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb003f6ce69a'
down_revision = '0a0cd43fd499'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
