"""empty message

Revision ID: cd58aa6ac7d1
Revises: 9afa92c42afe
Create Date: 2023-04-27 17:39:06.151109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd58aa6ac7d1'
down_revision = '9afa92c42afe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
