"""empty message

Revision ID: cfcdd0f45bd1
Revises: a5b1f52da296
Create Date: 2023-04-25 19:56:03.770790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfcdd0f45bd1'
down_revision = 'a5b1f52da296'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
