"""empty message

Revision ID: d0ee76a0886b
Revises: e5c02b8c54ec
Create Date: 2023-04-24 23:13:51.797663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0ee76a0886b'
down_revision = 'e5c02b8c54ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
