"""empty message

Revision ID: d127fe58cbfa
Revises: 6e9dfb00f1d6
Create Date: 2023-04-27 22:22:22.965144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd127fe58cbfa'
down_revision = '6e9dfb00f1d6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
