"""empty message

Revision ID: d1444580a551
Revises: 61bab7cb85a3
Create Date: 2023-04-28 00:15:24.710306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1444580a551'
down_revision = '61bab7cb85a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
