"""empty message

Revision ID: d2481f2e7225
Revises: 6af650c0fb55
Create Date: 2023-04-25 19:36:36.586720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2481f2e7225'
down_revision = '6af650c0fb55'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
