"""empty message

Revision ID: d33f3a5774ad
Revises: 9a8c09202c9b
Create Date: 2023-04-27 16:23:05.006853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd33f3a5774ad'
down_revision = '9a8c09202c9b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
