"""empty message

Revision ID: d5e1a0fd667d
Revises: 89a6459c31ba
Create Date: 2023-04-24 20:50:07.690530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5e1a0fd667d'
down_revision = '89a6459c31ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
