"""empty message

Revision ID: d5e34416d804
Revises: e2c34759f48d
Create Date: 2023-04-25 12:09:11.144939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5e34416d804'
down_revision = 'e2c34759f48d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
