"""empty message

Revision ID: d605ea58cc4c
Revises: 76a2db8d989c
Create Date: 2023-04-24 23:06:28.687827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd605ea58cc4c'
down_revision = '76a2db8d989c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
