"""empty message

Revision ID: d7dc2b761757
Revises: cb003f6ce69a
Create Date: 2023-04-27 19:17:49.061164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7dc2b761757'
down_revision = 'cb003f6ce69a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
