"""empty message

Revision ID: d8c68e12cbea
Revises: 5a3c30282fb5
Create Date: 2023-04-25 23:46:28.282147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8c68e12cbea'
down_revision = '5a3c30282fb5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
