"""empty message

Revision ID: d8d47ae6e3fc
Revises: a4bb3b7a835b
Create Date: 2023-04-27 21:48:38.048444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8d47ae6e3fc'
down_revision = 'a4bb3b7a835b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
