"""empty message

Revision ID: d8f806c550e7
Revises: 0241f2d5ce60
Create Date: 2023-04-25 22:41:43.417935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8f806c550e7'
down_revision = '0241f2d5ce60'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
