"""empty message

Revision ID: da6153a7c58e
Revises: 2c82946df0fe
Create Date: 2023-04-27 15:56:22.454080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da6153a7c58e'
down_revision = '2c82946df0fe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
