"""empty message

Revision ID: dbb89cf4386f
Revises: e50ed05a0c8e
Create Date: 2023-04-26 10:10:04.356258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbb89cf4386f'
down_revision = 'e50ed05a0c8e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
