"""empty message

Revision ID: df05aa0030fe
Revises: ef4d9a7b75c7
Create Date: 2023-04-27 18:37:02.350785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df05aa0030fe'
down_revision = 'ef4d9a7b75c7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
