"""empty message

Revision ID: e2c34759f48d
Revises: 0fa0058f97f9
Create Date: 2023-04-25 11:33:06.806496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2c34759f48d'
down_revision = '0fa0058f97f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
