"""empty message

Revision ID: e2d461fab251
Revises: bbfccbbc54bb
Create Date: 2023-04-25 17:11:44.094270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2d461fab251'
down_revision = 'bbfccbbc54bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
