"""empty message

Revision ID: e3663fb80a02
Revises: e51bfe577156
Create Date: 2023-04-25 00:00:13.890378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3663fb80a02'
down_revision = 'e51bfe577156'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
