"""empty message

Revision ID: e50ed05a0c8e
Revises: 68751d09b017
Create Date: 2023-04-26 10:02:26.166045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e50ed05a0c8e'
down_revision = '68751d09b017'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
