"""empty message

Revision ID: e51bfe577156
Revises: ef32418d65ca
Create Date: 2023-04-24 23:50:33.273610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e51bfe577156'
down_revision = 'ef32418d65ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
