"""empty message

Revision ID: e5c02b8c54ec
Revises: d605ea58cc4c
Create Date: 2023-04-24 23:11:21.863801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5c02b8c54ec'
down_revision = 'd605ea58cc4c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
