"""empty message

Revision ID: eaf83f2f36ad
Revises: 92cbc6909aeb
Create Date: 2023-04-25 19:01:54.232181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaf83f2f36ad'
down_revision = '92cbc6909aeb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
