"""empty message

Revision ID: eb18c3d75db5
Revises: 20bdf420de63
Create Date: 2023-04-26 00:31:30.089349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb18c3d75db5'
down_revision = '20bdf420de63'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
