"""empty message

Revision ID: ed94b4839124
Revises: ab1ba9023ded
Create Date: 2023-04-27 21:37:24.108771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed94b4839124'
down_revision = 'ab1ba9023ded'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
