"""empty message

Revision ID: ef4d9a7b75c7
Revises: 7ece4129ca9f
Create Date: 2023-04-27 18:28:07.458223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef4d9a7b75c7'
down_revision = '7ece4129ca9f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
