"""empty message

Revision ID: ef6f30338ebc
Revises: 6b5c12802dc7
Create Date: 2023-04-25 20:59:31.975053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef6f30338ebc'
down_revision = '6b5c12802dc7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
