"""empty message

Revision ID: ef876385cda4
Revises: 7d9776ee7629
Create Date: 2023-04-27 21:56:23.034301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef876385cda4'
down_revision = '7d9776ee7629'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
