"""empty message

Revision ID: efa921da80bf
Revises: df05aa0030fe
Create Date: 2023-04-27 18:41:20.631964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efa921da80bf'
down_revision = 'df05aa0030fe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
