"""empty message

Revision ID: f0521f222d87
Revises: 8b0af14bdfa3
Create Date: 2023-04-26 08:47:04.052234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0521f222d87'
down_revision = '8b0af14bdfa3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
