"""empty message

Revision ID: f52f9a521ee5
Revises: 7a6eecb75551
Create Date: 2023-04-24 21:48:46.211037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f52f9a521ee5'
down_revision = '7a6eecb75551'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
