"""empty message

Revision ID: f5b95f529ca6
Revises: 7ccff4ebd3c4
Create Date: 2023-04-26 22:02:13.586719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5b95f529ca6'
down_revision = '7ccff4ebd3c4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
