"""empty message

Revision ID: f607ccbcc762
Revises: 1376b94aea40
Create Date: 2023-04-26 08:38:12.591411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f607ccbcc762'
down_revision = '1376b94aea40'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
