"""empty message

Revision ID: fa6133043638
Revises: d0322d8e1d5a
Create Date: 2023-04-26 00:11:22.038241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa6133043638'
down_revision = 'd0322d8e1d5a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
