"""empty message

Revision ID: fc0abce506f9
Revises: ab93aaf83b54
Create Date: 2023-04-27 14:25:57.901040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc0abce506f9'
down_revision = 'ab93aaf83b54'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
