"""empty message

Revision ID: fcdffe5b0535
Revises: f6256307c6c7
Create Date: 2023-04-25 21:59:10.088791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcdffe5b0535'
down_revision = 'f6256307c6c7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
