"""empty message

Revision ID: fe42a1d4a791
Revises: 9291a5a265fc
Create Date: 2023-04-25 19:17:14.248346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe42a1d4a791'
down_revision = '9291a5a265fc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
